### ISSUE TITLE
Not Scorlling

### ISSUE THREAD

**Issue by MattIPv4** [mrphilipandrews/jquery.smoothwheel#17]
Can't Get It To Scroll On My Site, Testing On The 404 Page

https://www.mattcowley.co.uk/404/

its should be scrolling on the body, but it just blocks mousewheel scrolling all together.

**Comment by houmam86** [comment]
The same problem on Ubuntu 15.04 / Firefox 39.

It just block scrolling. It works on Chrome and Opera.

**Comment by MattIPv4** [comment]
Link no longer active, issue seems to be resolved.
