### ISSUE TITLE
Cross Browser Scrolling

### ISSUE THREAD

**Issue by DonDi1989** [mrphilipandrews/jquery.smoothwheel#6]
Plugin doesn't work in firefox and IE, only in Google Chrome. Is there any way to resolve this problem. I have use:

$("html, body").smoothWheel();

Regards

**Comment by rufncrus** [comment]
Hi DonDi1989!

I just tested demo (http://fatlinesofcode.github.io/jquery.smoothwheel/demo/smoothwheel.html) in most recent version of IE, Firefox and it worked for me. What versions specifically is it not working in?

**Comment by noptoboggan** [comment]
If the desire is to smooth scroll the entire document, IE and Firefox overflow in to `html`, while WebKit overflows in to `body`.

Calling `smoothWheel` on both does not seem like a good idea, attaching scroll listeners to both and wasting execution time.

Best to detect where the overflow is and call `smoothWheel` there, instead of checking the user agent for WebKit.

``` javascript
$(document.documentElement.scrollHeight > document.documentElement.clientHeight ? 'html' : 'body').smoothWheel();
```

A couple things to keep in mind. This is intended for full page smooth scrolling, and can be affected by styles on the `html` and `body` tags.

Below is the same functionality in a more readable format.

``` javascript
var overflowInHtml = document.documentElement.scrollHeight > document.documentElement.clientHeight;
var scrollingTag = overflowInHtml ? 'html' : 'body';
$(scrollingTag).smoothWheel();
```

**Comment by noptoboggan** [comment]
In addition to my previous comment, this pending pull request has updated the code to work with `window`.

https://github.com/mirikle/jquery.smoothwheel/blob/0b7dd07751387c5d4aaec9259b117a2e5e226abf/src/jquery.smoothwheel.js

Making the cross browser page scrolling solution.

``` javascript
$(window).smoothWheel();
```

**Comment by kunal-creative** [comment]
Hello

I am not sure which part i am missing. I used the latest js from 
https://github.com/mirikle/jquery.smoothwheel/blob/0b7dd07751387c5d4aaec9259b117a2e5e226abf/src/jquery.smoothwheel.js

Now in html i use
1:  var overflowInHtml = document.documentElement.scrollHeight > document.documentElement.clientHeight;
var scrollingTag = overflowInHtml ? 'html' : 'body';
$(scrollingTag).smoothWheel();

It works in firefox,IE not in chrome

2: $(window).smoothScroll();
Not working in any browser. 

Please help. Thanks

**Comment by noptoboggan** [comment]
@kunal-creative The link you provided was a pull request intending to add support for window scrolling. Have you tried with the latest version of the main fork [here](https://github.com/fatlinesofcode/jquery.smoothwheel)? Check if the following works in the user agents you're concerned with using the main fork.

``` javascript
$('html, body').smoothWheel();
```

If it does, that would indicate the conditional setting `overflowInHtml` may not be returning the desired value on your site for the user agents where it did not work before. Without seeing the site, its markup structure and CSS it is difficult to assist beyond this.

**Comment by noptoboggan** [comment]
@kunal-creative Also, there was a typo in my comment about the pull request, should have been:

``` javascript
$(window).smoothWheel();
```

My apologies.

**Comment by kunal-creative** [comment]
@R-eenignE  Thank you. It works for me.
